name: This custom workflow is trigger via HTTP 
on:
  repository_dispatch:
    types: [on_demand_test]
jobs:
  dumpContext:
    name: Dump context and payload
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}"
        run: echo "$PAYLOAD"
      - name: Echo Parameters
        env: 
          NAME: ${{ github.event.client_payload.name }}
          SURNAME: ${{ github.event.client_payload.surname }}
        run: echo "name=$NAME surname=$SURNAME"
      
